Test
vanswei/homework pull request #5
Opened 2023-07-06 05:50 UTC by vanswei

这是程序3的单元测试代码

2023-07-06 08:10 UTC, vincent-ng requested changes

2023-07-06 08:10 UTC, vincent-ng commented on test.js
> +            const R = 50 // 假设R的值为50
这个地方没法假设吧，服务器的R值测试程序是不知道的。
可以在服务器模块上增加对R值的设定，然后单元测试里进行断言。

2023-07-06 08:12 UTC, vanswei commented on test.js
> +            const R = 50 // 假设R的值为50
好的，我在修改一下。

2023-07-07 01:09 UTC, vincent-ng requested changes

2023-07-07 01:09 UTC, vincent-ng commented on homework3.js
> +    const randomNumber = 50 //将值定为50，为单元测试提供准确判断
这行去掉

2023-07-07 01:09 UTC, vincent-ng commented on test.js
> +            client.set('R', 50)
这里放在before里会更好

2023-07-07 06:12 UTC, vincent-ng approved these changes

2023-07-07 06:12 UTC, vincent-ng commented on test.js
> +const getAsync = promisify(client.get).bind(client)
这个变量没用到，可以删掉。
redis库的接口默认就是async的，不需要promisify。（早些年async还没成为标准的时候才需要这样写）

2023-07-07 06:20 UTC, vanswei commented on test.js
> +const getAsync = promisify(client.get).bind(client)
收到，已完成修改。
可能是查到的资料是比较老一点

2023-07-07 08:33 UTC, vincent-ng approved these changes

2023-07-10 07:20 UTC, merged